# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    Blogger\BlogBundle\Controller\RegistrationController:
        class: Blogger\BlogBundle\Controller\RegistrationController
        autowire: true # or define your controller constructor and configure its arguments explicitly
        tags:
            - name: controller.service_arguments    
