blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Post:index }
    
registro_form:
    path:  /registro
    defaults: { _controller: BloggerBlogBundle:Security:register }
    
forget_password:
    path:  /forget_password
    defaults: { _controller: BloggerBlogBundle:Default:resetPass }
    
admin:
  path: /admin
  defaults: { _controller: BloggerBlogBundle:Security:login }

login_check:
   path: /login_check
 
logout:
  path: /logout
  
secure:
  path: /secure
  defaults: { _controller: BloggerBlogBundle:Security:secure }

registro_blog:
  path: /secure/post/crear
  defaults: { _controller: BloggerBlogBundle:Post:newPost }

list_posts:
  path: /secure/post/list
  defaults: { _controller: BloggerBlogBundle:Post:list }

edit_post:
  path: /secure/post/edit/{post}
  defaults: { _controller: BloggerBlogBundle:Post:edit }
  
delete_post:
  path: /post/delete/{post}
  defaults: { _controller: BloggerBlogBundle:Post:delete }    

list_users:
  path: /secure/user/list
  defaults: { _controller: BloggerBlogBundle:User:index }
  
edit_user:
  path: /secure/user/edit/{user}
  defaults: { _controller: BloggerBlogBundle:User:edit }
  
delete_user:
  path: /secure/user/delete/{user}
  defaults: { _controller: BloggerBlogBundle:User:delete }